<a href="https://colab.research.google.com/github/SeyoungYoo/DLforEveryone/blob/main/ML_Lab01_TensorFlow_install_basic_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##**TensorFlow 설치**

In [1]:
pip install --upgrade tensorflow

Requirement already up-to-date: tensorflow in /usr/local/lib/python3.7/dist-packages (2.4.1)


In [2]:
pip install --upgrade tensorflow-gpu

     |████████████████████████████████| 394.3MB 43kB/s 


**TensorFlow import해주기**

In [3]:
import tensorflow as tf

**TF 버전 확인**

In [4]:
tf.__version__

'2.4.1'

In [5]:
# Create a constant op
# This op is added as a node to the default graph
hello = tf.constant("Hello, TensorFlow!")

tf.print(hello)

Hello, TensorFlow!


##**Computational Graph**

In [6]:
node1 = tf.constant(3.0,tf.float32)
node2 = tf.constant(4.0)    # also tf.float32 implicitly
node3 = tf.add(node1, node2)    # node3 = node1+node2

In [7]:
print("node1:", node1, "node2:", node2)
print("node3:", node3)

node1: tf.Tensor(3.0, shape=(), dtype=float32) node2: tf.Tensor(4.0, shape=(), dtype=float32)
node3: tf.Tensor(7.0, shape=(), dtype=float32)


In [8]:
tf.print("node1:",node1,"node2:",node2)
tf.print("node3:",node3)

node1: 3 node2: 4
node3: 7


In [10]:
import tensorflow as tf
import numpy as np

@tf.function
def adder(a,b):
  return a+b

A = tf.constant(1)
B = tf.constant(2)
print(adder(A,B))

C = tf.constant([1,2])
D = tf.constant([3,4])
print(adder(C,D))

E = tf.constant([[1,2,3],[4,5,6]])
F = tf.constant([[2,3,4],[5,6,7]])
print(adder(E,F))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(
[[ 3  5  7]
 [ 9 11 13]], shape=(2, 3), dtype=int32)


In [11]:
tf.print(adder(A,B))
tf.print(adder(C,D))
tf.print(adder(E,F))

3
[4 6]
[[3 5 7]
 [9 11 13]]
