<a href="https://colab.research.google.com/github/SeyoungYoo/DLforEveryone/blob/main/Season01/ML_Lab07_1_Dataset_learning_rate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.15.0

     |████████████████████████████████| 412.3MB 34kB/s 
     |████████████████████████████████| 512kB 34.1MB/s 
     |████████████████████████████████| 3.8MB 26.2MB/s 
     |████████████████████████████████| 51kB 4.6MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp37-none-any.whl size=7540 sha256=f567965beb94f98e9e696c70707fdf35014d2efebf81bf608336b13029094a49
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.12.1 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninsta

##**Training and Test Datasets**

* training dataset으로 model을 학습시키고,
* model이 한 번도 본 적 없는 dataset인 test dataset으로 model를 시험한다.

In [2]:
import tensorflow as tf

In [3]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [4]:
# Evaluation our model using this test dataset
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [5]:
X = tf.placeholder("float", [None,3])
Y = tf.placeholder("float", [None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [6]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [7]:
# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [8]:
# Launch graph
with tf.Session() as sess:
  # Initialize Tensorflow variables
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                  feed_dict={X:x_data, Y: y_data})
    print(step, cost_val, W_val)

  # predict
  print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
  # Calculate the accuracy
  print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 5.4370465 [[-0.6974268   0.94551456  0.20183307]
 [ 1.0279273  -1.5400364   0.53161013]
 [-0.05146384  2.8118153   1.3226922 ]]
1 3.0689783 [[-0.6737167   0.94660914  0.1770284 ]
 [ 1.1870362  -1.4769207   0.3093855 ]
 [ 0.10895759  2.8461866   1.1278994 ]]
2 2.108223 [[-0.6560639   0.9162034   0.18978134]
 [ 1.3134509  -1.5839309   0.28998083]
 [ 0.24586225  2.7157784   1.121403  ]]
3 1.631681 [[-0.65225357  0.90420556  0.19796883]
 [ 1.3610944  -1.5924714   0.25087798]
 [ 0.31779665  2.6785402   1.0867068 ]]
4 1.5658803 [[-0.65976775  0.8961232   0.21356541]
 [ 1.3433597  -1.5790306   0.2551719 ]
 [ 0.3303196   2.662581    1.090143  ]]
5 1.5500901 [[-0.6662108   0.88854575  0.22758585]
 [ 1.3311583  -1.5631315   0.25147414]
 [ 0.34761435  2.649102    1.0863272 ]]
6 1.535139 [[-0.6727404   0.8809968   0.24166438]
 [ 1.3178896  -1.5470906   0.24870194]
 [ 0.36370286  2.6358187   1.083522  ]]
7 1.5203875 [[-0.6791155   0.873445    0.25559124]
 [ 1.3049438  -1.5311205   0.24567756]
 [ 

##**Learning rate**

* learning_rate가 너무 클 경우 발산할 수가 있다.
* 반면 learning_rate가 너무 작을 경우 수렴지점까지 가지 못하고 중간에 멈춰서 정확한 결과가 나오지 않을 수 있다.

###**Big learning_rate**

In [9]:
import tensorflow as tf

In [10]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [11]:
# Evaluation our model using this test dataset
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [12]:
X = tf.placeholder("float", [None,3])
Y = tf.placeholder("float", [None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [13]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1.5).minimize(cost)

In [14]:
# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [15]:
# Launch Test
with tf.Session() as sess:
  # Initialize Tensorflow variables
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                  feed_dict={X: x_data, Y: y_data})
    print(step, cost_val, W_val)

  # predict
  print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
  # accuracy
  print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 2.213242 [[-1.2430067   1.8393836   1.3513334 ]
 [-2.2687294   1.4736583  -0.3909073 ]
 [-2.9758906   0.34155142  0.9965587 ]]
1 13.355429 [[-0.86800694  1.0249419   1.7907753 ]
 [ 0.16877007 -2.1970727   0.8423246 ]
 [-0.5383911  -2.8674607   1.7680712 ]]
2 20.73497 [[-0.4932298   1.5874417   0.85349846]
 [ 2.6058133   0.42792678 -4.2197185 ]
 [ 1.8988748  -0.0549612  -3.4816942 ]]
3 18.603218 [[-1.6176157  2.1493275  1.4159985]
 [-1.5179489  3.0516884 -2.7197185]
 [-2.2254996  2.7569132 -2.1691942]]
4 26.615952 [[-1.2426157   1.2118275   1.9784985 ]
 [ 0.91955113 -0.88581157 -1.2197185 ]
 [ 0.21200037 -0.9930868  -0.8566942 ]]
5 6.4433928 [[-2.3133616   1.7698069   2.4912653 ]
 [-3.093828    1.7298448   0.17800462]
 [-3.8513145   1.8143566   0.3991773 ]]
6 19.937225 [[-1.9383616   0.86386263  3.0222096 ]
 [-0.65632796 -2.1426463   1.6129959 ]
 [-1.4138145  -1.9014885   1.6775225 ]]
7 26.0711 [[-1.5633616   1.4263626   2.0847096 ]
 [ 1.7811718   0.4823537  -3.4495041 ]
 [ 1.0236855 

* learning_rate이 너무 클 경우 결과가 제대로 나오지 않는다.

###**Small Learning rate**

In [16]:
import tensorflow as tf

In [17]:
x_data = [[1,2,1],[1,3,2],[1,3,4],[1,5,5],[1,7,5],[1,2,5],[1,6,6],[1,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [18]:
# Evaluation our model using this test dataset
x_test = [[2,1,1],[3,1,2],[3,3,4]]
y_test = [[0,0,1],[0,0,1],[0,0,1]]

In [19]:
X = tf.placeholder("float", [None,3])
Y = tf.placeholder("float", [None,3])
W = tf.Variable(tf.random_normal([3,3]))
b = tf.Variable(tf.random_normal([3]))

In [22]:
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

In [23]:
# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [24]:
# Launch Test
with tf.Session() as sess:
  # Initialize Tensorflow variables
  sess.run(tf.global_variables_initializer())
  for step in range(201):
    cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                  feed_dict={X: x_data, Y: y_data})
    print(step, cost_val, W_val)

  # predict
  print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
  # accuracy
  print("Accuracy:", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 12.066111 [[ 0.8404364   1.3830751   0.06328064]
 [ 1.2676092   0.5187784  -0.36896977]
 [ 2.096544   -0.6760102  -0.90144074]]
1 12.066111 [[ 0.8404364   1.3830751   0.06328064]
 [ 1.2676092   0.5187784  -0.36896977]
 [ 2.096544   -0.6760102  -0.90144074]]
2 12.066111 [[ 0.8404364   1.3830751   0.06328064]
 [ 1.2676092   0.5187784  -0.36896977]
 [ 2.096544   -0.6760102  -0.90144074]]
3 12.066111 [[ 0.8404364   1.3830751   0.06328064]
 [ 1.2676092   0.5187784  -0.36896977]
 [ 2.096544   -0.6760102  -0.90144074]]
4 12.066111 [[ 0.8404364   1.3830751   0.06328064]
 [ 1.2676092   0.5187784  -0.36896977]
 [ 2.096544   -0.6760102  -0.90144074]]
5 12.066111 [[ 0.8404364   1.3830751   0.06328064]
 [ 1.2676092   0.5187784  -0.36896977]
 [ 2.096544   -0.6760102  -0.90144074]]
6 12.066111 [[ 0.8404364   1.3830751   0.06328064]
 [ 1.2676092   0.5187784  -0.36896977]
 [ 2.096544   -0.6760102  -0.90144074]]
7 12.066111 [[ 0.8404364   1.3830751   0.06328064]
 [ 1.2676092   0.5187784  -0.36896977]


* learning_rate이 너무 작아도 제대로 된 결과값이 나오지 않는다.

##**Normalized inputs**

* data들의 편차가 너무 심할 경우 normalized 하여 데이터가 모델을 튕겨나갈 확률을 줄인다.

###**Non_normalized inputs**

In [25]:
import tensorflow as tf
import numpy as np

In [26]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
              [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
              [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
              [816, 820.958984, 1008100, 815.48999, 819.23999],
              [819.359985, 823, 1188100, 818.469971, 818.97998],
              [819, 823, 1198100, 816, 820.450012],
              [811.700012, 815.25, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [27]:
x_data = xy[:,0:-1]
y_data = xy[:, [-1]]

In [29]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None,4])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [30]:
hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [31]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [32]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
  cost_val, hy_val, _ = sess.run(
      [cost, hypothesis, train], feed_dict = {X: x_data, Y: y_data})
  print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
1501 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1502 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1503 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1504 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1505 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1506 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1507 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1508 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1509 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1510 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1511 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
1512 Co

###**Normalized inputs**

In [34]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [35]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
              [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
              [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
              [816, 820.958984, 1008100, 815.48999, 819.23999],
              [819.359985, 823, 1188100, 818.469971, 818.97998],
              [819, 823, 1198100, 816, 820.450012],
              [811.700012, 815.25, 1098100, 809.780029, 813.669983],
              [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [36]:
x_data = xy[:,0:-1]
y_data = xy[:,[-1]]

In [37]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None,4])
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [38]:
hypothesis = tf.matmul(X,W)+b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [39]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [40]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
  print(step, "Cost: ",cost_val,"\nPrediction:\n", hy_val)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
1501 Cost:  0.5478046 
Prediction:
 [[ 0.2397381 ]
 [ 2.3996196 ]
 [ 1.0913697 ]
 [-0.3528179 ]
 [ 0.3292513 ]
 [ 0.27746892]
 [-0.48459375]
 [ 0.21918774]]
1502 Cost:  0.54780304 
Prediction:
 [[ 0.23973835]
 [ 2.3996162 ]
 [ 1.091368  ]
 [-0.35281765]
 [ 0.32925057]
 [ 0.2774682 ]
 [-0.48459375]
 [ 0.21918643]]
1503 Cost:  0.5478012 
Prediction:
 [[ 0.23973858]
 [ 2.3996124 ]
 [ 1.0913662 ]
 [-0.35281742]
 [ 0.32924998]
 [ 0.2774675 ]
 [-0.48459375]
 [ 0.219185  ]]
1504 Cost:  0.5477996 
Prediction:
 [[ 0.23973894]
 [ 2.399609  ]
 [ 1.0913644 ]
 [-0.35281718]
 [ 0.32924926]
 [ 0.27746677]
 [-0.48459375]
 [ 0.21918368]]
1505 Cost:  0.5477978 
Prediction:
 [[ 0.23973918]
 [ 2.3996053 ]
 [ 1.0913626 ]
 [-0.35281694]
 [ 0.32924867]
 [ 0.27746618]
 [-0.48459375]
 [ 0.21918237]]
1506 Cost:  0.5477962 
Prediction:
 [[ 0.23973942]
 [ 2.399602  ]
 [ 1.091361  ]
 [-0.3528167 ]
 [ 0.32924807]
 [ 0.27746534]
 [-0.48459375]
 [ 0.21918106]]
1507 Cost:  0.5477943

* normalized 하지 않았을 때는 결과가 제대로 나오지 않았지만 하고 난 후에는 결과가 제대로 나온다.