<a href="https://colab.research.google.com/github/SeyoungYoo/DLforEveryone/blob/main/Season01/ML_Lab06_1_Softmax_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow==1.15.0

     |████████████████████████████████| 412.3MB 31kB/s 
     |████████████████████████████████| 512kB 39.2MB/s 
     |████████████████████████████████| 51kB 5.0MB/s 
     |████████████████████████████████| 3.8MB 42.7MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp37-none-any.whl size=7540 sha256=8d54aeb8ba6004fc0086cbf34c6987fe3d02b25a20c9c7cb59441a3d7f5fe18c
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.12.1 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninsta

In [ ]:
import tensorflow as tf

* y_data를 나타낼 때에는 one-hot encoding을 사용했다.

In [ ]:
x_data = [[1,2,1,1],[2,1,3,2],[3,1,3,4],[4,1,5,5],[1,7,5,5],[1,2,5,6],[1,6,6,6],[1,7,7,7]]
y_data = [[0,0,1],[0,0,1],[0,0,1],[0,1,0],[0,1,0],[0,1,0],[1,0,0],[1,0,0]]

In [ ]:
X = tf.placeholder("float", [None,4])
Y = tf.placeholder("float", [None,3])

In [ ]:
nb_classes = 3

In [ ]:
W = tf.Variable(tf.random_normal([4,nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

* softmax function 은 예측한 값을 0과 1 사이의 값(확률)으로 표현해주는 함수이다.
* 이때 softmax function을 거친 값들을 다 합하면 1이 된다.

In [ ]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X,W)+b)

In [ ]:
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [ ]:
# launch graph
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())

  for step in range(2001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
      print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}))
  
  print('-----------------------------')
  a = sess.run(hypothesis, feed_dict={X:[[1,11,7,9]]})
  print(a, sess.run(tf.arg_max(a,1)))
  print('-----------------------------')
  all = sess.run(hypothesis, feed_dict={X: [[1,11,7,9],[1,3,4,3],[1,1,0,1]]})
  print(all, sess.run(tf.arg_max(all,1)))

0 2.9334166
200 0.5785986
400 0.47008878
600 0.39019972
800 0.31626984
1000 0.24927373
1200 0.22389056
1400 0.20376487
1600 0.18686128
1800 0.172463
2000 0.16005646
-----------------------------
[[7.8006969e-03 9.9219066e-01 8.6019827e-06]] [1]
-----------------------------
[[7.8006969e-03 9.9219066e-01 8.6020000e-06]
 [8.3292609e-01 1.5575446e-01 1.1319408e-02]
 [1.5226050e-08 3.6853921e-04 9.9963140e-01]] [1 0 2]
