<a href="https://colab.research.google.com/github/SeyoungYoo/DLforEveryone/blob/main/Season01/ML_Lab04_1_Multi_variable_linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tensorflow==1.15.0

     |████████████████████████████████| 412.3MB 44kB/s 
     |████████████████████████████████| 512kB 51.7MB/s 
     |████████████████████████████████| 3.8MB 31.9MB/s 
     |████████████████████████████████| 51kB 4.3MB/s 
  Created wheel for gast: filename=gast-0.2.2-cp37-none-any.whl size=7540 sha256=bece3ae4aa35de2d7fa0301349a683a1952e61c70d42f66f8b69dc2fc9f54dbb
  Stored in directory: /root/.cache/pip/wheels/5c/2e/7e/a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd
Successfully built gast
ERROR: tensorflow-probability 0.12.1 has requirement gast>=0.3.2, but you'll have gast 0.2.2 which is incompatible.
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estimator-2.4.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3.3
  Found existing installation: tensorboard 2.4.1
    Uninstalling tensorboard-2.4.1:
      Successfully uninsta

##**여러 개의 변수를 통해 학습하기**

###**Matrix를 사용하지 않고 실행**

* 3번의 시험 점수를 가지고 final 점수 예측

In [2]:
import tensorflow as tf

In [3]:
# 변수 입력
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75., 93., 90., 100.,70.]
y_data = [152., 185., 180.,196.,142.]

In [5]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

In [6]:
w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [7]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [8]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
  cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                 feed_dict = {x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
  if step % 10 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  4507.9307 
Prediction:
 [ 89.030655 114.9416   109.18251  119.72171   88.77556 ]
10 Cost:  3.2711415 
Prediction:
 [148.40988 186.29883 179.49835 196.29288 143.20099]
20 Cost:  3.215458 
Prediction:
 [148.59598 186.51035 179.71313 196.52573 143.36018]
30 Cost:  3.2010906 
Prediction:
 [148.60297 186.50664 179.71579 196.52757 143.3552 ]
40 Cost:  3.1867993 
Prediction:
 [148.60939 186.50227 179.71779 196.52873 143.34972]
50 Cost:  3.1725903 
Prediction:
 [148.61577 186.4979  179.71977 196.52985 143.34424]
60 Cost:  3.1584697 
Prediction:
 [148.62215 186.49356 179.72179 196.531   143.33879]
70 Cost:  3.1444025 
Prediction:
 [148.62854 186.48926 179.72379 196.53217 143.33337]
80 Cost:  3.1304262 
Prediction:
 [148.63486 186.4849  179.72574 196.53328 143.32794]
90 Cost:  3.1165178 
Prediction:
 [148.6412  186.4806  179.72774 196.53442 143.32256]
100 Cost:  3.1026952 
Prediction:
 [148.6475  186.4763  179.7297  196.53554 143.31717]
110 Cost:  3.088939 
Prediction:
 [148.65381 186.4

###**Matrix를 사용하고 실행**

* matrix를 사용하면 데이터셋을 간단하게 넣을 수 있다.

In [9]:
import tensorflow as tf

In [10]:
x_data = [[73.,80.,75.], [93.,88.,93.], [89.,91.,90.],
          [96.,98.,100.], [73.,66.,70.]]
y_data = [[152.],[185.],[180.],[196.],[142.]]

In [11]:
# placeholders for a tensor that will be alwways fed.
X = tf.placeholder(tf.float32, shape=[None,3])
Y = tf.placeholder(tf.float32, shape=[None,1])

In [12]:
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [14]:
# Hypothesis
hypothesis = tf.matmul(X,W) + b
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [15]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [16]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [17]:
for step in range(2001):
  cost_val, hy_val, _ = sess.run(
      [cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
  if step % 10 == 0:
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  75353.15 
Prediction:
 [[ -86.550644]
 [-111.87151 ]
 [-106.013115]
 [-116.5488  ]
 [ -86.55279 ]]
10 Cost:  16.247463 
Prediction:
 [[156.24081]
 [179.97446]
 [181.53276]
 [196.58308]
 [136.058  ]]
20 Cost:  15.474831 
Prediction:
 [[156.96027]
 [180.86789]
 [182.39816]
 [197.5271 ]
 [136.74525]]
30 Cost:  15.392387 
Prediction:
 [[156.94734]
 [180.88094]
 [182.39615]
 [197.52652]
 [136.76099]]
40 Cost:  15.310339 
Prediction:
 [[156.93224]
 [180.89131]
 [182.39153]
 [197.5231 ]
 [136.77466]]
50 Cost:  15.228699 
Prediction:
 [[156.91718]
 [180.90167]
 [182.38693]
 [197.5197 ]
 [136.78831]]
60 Cost:  15.1475935 
Prediction:
 [[156.90213]
 [180.91196]
 [182.38234]
 [197.5163 ]
 [136.8019 ]]
70 Cost:  15.066897 
Prediction:
 [[156.88716]
 [180.92224]
 [182.37775]
 [197.51291]
 [136.81546]]
80 Cost:  14.986578 
Prediction:
 [[156.8722 ]
 [180.9325 ]
 [182.37317]
 [197.50952]
 [136.82898]]
90 Cost:  14.906774 
Prediction:
 [[156.85732]
 [180.94273]
 [182.36864]
 [197.50616]
 [136